package beautycache;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import beautycache.Beauty;
import beautycache.BeautyDao;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig beautyDaoConfig;

    private final BeautyDao beautyDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        beautyDaoConfig = daoConfigMap.get(BeautyDao.class).clone();
        beautyDaoConfig.initIdentityScope(type);

        beautyDao = new BeautyDao(beautyDaoConfig, this);

        registerDao(Beauty.class, beautyDao);
    }
    
    public void clear() {
        beautyDaoConfig.getIdentityScope().clear();
    }

    public BeautyDao getBeautyDao() {
        return beautyDao;
    }

}
